### ISSUE TITLE
Invalid status code:0

### ISSUE THREAD

**Issue by JaimeChizavane** [jorditost/node-postgres-restapi#1]
Hi 

I'm facing the error status 500 : {"status":"error","message":"Invalid status code: 0"} while trying to get in postman the below GET request: 
http://_myvpsname_:3000/api/starships

It was not suppose to send me a JSON message with all the database content according the query in the queries.js? 

Is there anything that I'm not doing properly?

**Comment by jorditost** [comment]
Hi @JaimeChizavane,
yes, if you did start your PostGRE Database and imported the `data/startrek.sql` database to it (in the README.rd you will find how to do this), you should get this:

```
{"status":"success","data":[{"id":1,"name":"USS Enterprise","registry":"NCC-1701","affiliation":"United Federation of Planets Starfleet","launched":2258,"class":"Constitution","captain":"James T. Kirk"}],"message":"Retrieved all starships"}
```

Have you checked if your database is already working? Or if the port is right?

**Comment by JaimeChizavane** [comment]
Hi @jorditost,

The database is running and I have even remove all the security requirements and currently the database config is setup to trust all connections through port 5432, I even manage to run queries connecting my database server but when I run a select query the result is the below:

SELECT * FROM public.starships;
1;"USS Enterprise";"NCC-1701";"United Federation of Planets Starfleet";2258;"Constitution";"James T. Kirk"

What means that the table is there but when I go to POSTMAN and run GET 
http://myvps:3000/api/starships

The error is the below: 
{"status":"error","message":"Invalid status code: 0"}

On terminal comes something like:
GET /api/starships **500** 45.167 ms - 53

Showing that there is something wrong with the database.

**Comment by jorditost** [comment]
It seems to be something with your database then. Maybe you should check your database or server permissions. Is your database in a different server than the API server? Actually, the CORS are configured in the file `server.js` to allow that.
