### ISSUE TITLE
Port 3000 blocked Error: listen EADDRINUSE :::3000

### ISSUE THREAD

**Issue by lakiefer** [jorditost/node-postgres-restapi#2]
First thank you for the project.

I get this error every time after pressing ctrl+x and trying to run npm start again.
I need to restart the server to free the port again.
Can't manage it by killing the process with the right PID.

Do you have any suggestions?

Finally I just added nodemon to the project and don't have any issues anymore. Thank you anyway :)

**Comment by JustGiveItATry** [comment]
Does someone now how to allow GET,PUT,POST,DELETE?

In Postman it is working, but my Angular App calls DELETE and reaches OPTIONS on the server. I don't really now why.
